language: php

php:
  - 7.2

sudo: false

services:
  - mysql

env:
  global:
    - SHOPWARE_DIRECTORY=${HOME}/shopware
    - PLUGIN_DIRECTORY=${SHOPWARE_DIRECTORY}/custom/plugins

before_script:
  - composer config github-oauth.github.com ${GH_TOKEN}
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
  - mkdir RawPrice
  - rsync -av --progress ./* RawPrice --exclude RawPrice
  - git clone https://github.com/shopware/development.git
  - cd development
  - composer install
  - git clone https://github.com/shopware/platform.git
  - ./psh.phar init
  - mv RawPrice custom/plugins/
  - php bin/console plugin:install --activate Raw\\\\CustomerPrice\\\\CustomerPrice

script:
  - pwd
  - ls

deploy:
  github_token: $GH_TOKEN

