language: php

php:
  - 7.2

sudo: false

services:
  - mysql

env:
  matrix:
    - SHOPWARE_VERSION="5.5"
  global:
    - PLUGIN_NAME=FroshDataTableLayout
    - SHOPWARE_DIRECTORY=${HOME}/shopware
    - PLUGIN_DIRECTORY=${SHOPWARE_DIRECTORY}/custom/plugins

cache:
  directories:
    - ${HOME}/.composer/cache/files

install:
  - composer install

before_script:
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
  - git clone https://github.com/shopware/development.git
  - cd development
  - git clone https://github.com/shopware/platform.git
  - php bin/setup



